export const MainTypes = {
    // tag
    TAG_UPDATE_PROPS: 'TAG_UPDATE_PROPS',
    TAG_RESET_PROPS: 'TAG_RESET_PROPS',
    UPDATE_TAG_OPTION: 'UPDATE_TAG_OPTION',
    ADD_TAG_OPTION: 'ADD_TAG_OPTION',
    REMOVE_TAG_OPTION: 'REMOVE_TAG_OPTION',
    RESET_TAG: 'RESET_TAG',
    // number
    NUMBER_UPDATE_PROPS: 'NUMBER_UPDATE_PROPS',
    NUMBER_RESET_PROPS: 'NUMBER_RESET_PROPS',
    ADD_NUMBER_OPTION: 'ADD_NUMBER_OPTION',
    UPDATE_NUMBER_OPTION: 'UPDATE_NUMBER_OPTION',
    REMOVE_NUMBER_OPTION: 'REMOVE_NUMBER_OPTION',
    RESET_NUMBER: 'RESET_NUMBER',
    // emphasizer
    EMPHASIZER_UPDATE_PROPS: 'EMPHASIZER_UPDATE_PROPS',
    EMPHASIZER_RESET_PROPS: 'EMPHASIZER_RESET_PROPS',
    EMPHASIZER_UPDATE_OPTIONS: 'EMPHASIZER_UPDATE_OPTIONS',
    EMPHASIZER_RESET_OPTIONS: 'EMPHASIZER_RESET_OPTIONS',
};
